<script>
	// your script goes here
</script>

<main class="container">
	<div class="card">
		<h1>Welcome to Kindle</h1>
	</div>
</main>

<style>
	main {
		height: 100vh;
		width: 100vw;
		display: grid;
		align-items: center;
		justify-items: center;
	}

	.card {
		/* Generated by https://generator.ui.glass/ */
		backdrop-filter: blur(25px) saturate(160%);
		-webkit-backdrop-filter: blur(25px) saturate(160%);
		background-color: rgba(0, 0, 0, 0.5);
		border-radius: 12px;
		border: 1px solid rgba(255, 255, 255, 0.125);

		padding: 5em;
	}

	:global(body) {
		background-color: #111927;
		background-image: radial-gradient(at 47% 33%, hsl(162, 77%, 40%) 0, transparent 59%),
			radial-gradient(at 82% 65%, hsl(218.33, 100%, 49%) 0, transparent 55%);
	}
</style>
